# Generated by Django 4.2.3 on 2023-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eClearanceAuth", "0005_studentprofile_date_joined"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office_title", models.CharField(max_length=30, unique=True)),
                (
                    "office_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={"verbose_name_plural": "Office", "db_table": "Office",},
        ),
    ]
