# Generated by Django 4.2.3 on 2023-07-12 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("eClearanceAuth", "0008_alter_office_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeprofile",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date_created",
            ),
            preserve_default=False,
        ),
    ]
