# Generated by Django 4.2.3 on 2023-07-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eClearanceAuth", "0010_departmentalclearance_cleared_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentalclearance",
            name="is_disapprove",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hostelclearance",
            name="is_disapprove",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internalauditclearance",
            name="is_disapprove",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="libraryclearance",
            name="is_disapprove",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sportclearance",
            name="is_disapprove",
            field=models.BooleanField(default=False),
        ),
    ]
