# Generated by Django 4.2.3 on 2023-07-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eClearanceAuth", "0011_departmentalclearance_is_disapprove_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentalclearance",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eClearanceAuth.studentclearance",
            ),
        ),
        migrations.AddField(
            model_name="hostelclearance",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eClearanceAuth.studentclearance",
            ),
        ),
        migrations.AddField(
            model_name="internalauditclearance",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eClearanceAuth.studentclearance",
            ),
        ),
        migrations.AddField(
            model_name="libraryclearance",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eClearanceAuth.studentclearance",
            ),
        ),
        migrations.AddField(
            model_name="sportclearance",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eClearanceAuth.studentclearance",
            ),
        ),
    ]
