# Generated by Django 4.2.3 on 2023-07-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eClearanceAuth",
            "0013_rename_student_departmentalclearance_clearance_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryclearance",
            name="cost_of_book_owe_departmental",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="libraryclearance",
            name="cost_of_book_owe_main",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
